-- ============================================================
-- Schema base legado (instalação limpa / Docker)
-- Compatível com a nova versão do Sistema Knoll
-- ============================================================

CREATE TABLE IF NOT EXISTS knoll_usuarios (
  cd_usrs INT NOT NULL PRIMARY KEY,
  nm_logn VARCHAR(40) NOT NULL,
  cd_pass VARCHAR(100) NULL,
  nm_usrs VARCHAR(80) NULL,
  cd_acss SMALLINT NULL DEFAULT 0,
  cd_modl_clnt SMALLINT NULL DEFAULT 0,
  in_tipo CHAR(1) NULL DEFAULT 'A',
  hr_matt_entr CHAR(5) NULL,
  hr_matt_saida CHAR(5) NULL,
  hr_vesp_entr CHAR(5) NULL,
  hr_vesp_saida CHAR(5) NULL,
  ds_email VARCHAR(120) NULL,
  cd_depr INT NULL,
  nivel INT NULL DEFAULT 1,
  UNIQUE KEY uk_knoll_usuarios_login (nm_logn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS knoll_configuracao (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nm_empr VARCHAR(100) NOT NULL DEFAULT '',
  ds_razao VARCHAR(100) NULL,
  nu_cnpj VARCHAR(18) NULL,
  nu_ie VARCHAR(20) NULL,
  nu_cep VARCHAR(10) NULL,
  nm_logr VARCHAR(100) NULL,
  ds_email VARCHAR(120) NULL,
  nu_logr VARCHAR(20) NULL,
  nm_barr VARCHAR(60) NULL,
  nm_munc VARCHAR(60) NULL,
  sg_estd CHAR(2) NULL,
  nu_telf VARCHAR(20) NULL,
  nu_telf2 VARCHAR(20) NULL,
  nu_fax VARCHAR(20) NULL,
  ultimo_servico INT NULL DEFAULT 0,
  ds_obs TEXT NULL,
  ds_logo VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS knoll_clientes (
  IDCLI INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(120) NULL,
  RAZAO VARCHAR(120) NULL,
  CPF VARCHAR(20) NULL,
  CGC VARCHAR(20) NULL,
  IE VARCHAR(20) NULL,
  TELEFONE VARCHAR(20) NULL,
  CELULAR VARCHAR(20) NULL,
  FAX VARCHAR(20) NULL,
  EMAIL VARCHAR(120) NULL,
  CEP VARCHAR(12) NULL,
  ENDERECO VARCHAR(150) NULL,
  COMPLEMENTO VARCHAR(150) NULL,
  BAIRRO VARCHAR(80) NULL,
  MUNICIPIO VARCHAR(80) NULL,
  ESTADO VARCHAR(2) NULL,
  TIPO VARCHAR(20) NULL,
  DATA_REG TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_clientes_nome (NOME),
  INDEX idx_clientes_municipio (MUNICIPIO),
  INDEX idx_clientes_bairro (BAIRRO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS knoll_funcionario (
  IDFUN INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(80) NULL,
  ENDERECO VARCHAR(80) NULL,
  COMPLEMENTO VARCHAR(40) NULL,
  BAIRRO VARCHAR(40) NULL,
  MUNICIPIO VARCHAR(40) NULL,
  UF VARCHAR(2) NULL,
  CEP VARCHAR(12) NULL,
  CPF VARCHAR(20) NULL,
  NASCIMENTO DATETIME NULL,
  IDENTIDADE VARCHAR(30) NULL,
  FONE VARCHAR(20) NULL,
  CELULAR VARCHAR(20) NULL,
  COMISSAO DOUBLE NULL,
  VALE DOUBLE NULL,
  TIPO VARCHAR(20) NULL,
  INDEX idx_funcionario_nome (NOME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS knoll_produtos (
  IDPRO INT NOT NULL PRIMARY KEY,
  DESCRICAO VARCHAR(120) NULL,
  MODELO VARCHAR(40) NULL,
  UNIDADE VARCHAR(10) NULL,
  CUSTO DOUBLE NULL DEFAULT 0,
  MARGEM DOUBLE NULL DEFAULT 0,
  ST VARCHAR(1) NULL DEFAULT 'A',
  OBS VARCHAR(255) NULL,
  MINIMO DOUBLE NULL DEFAULT 0,
  MAXIMO DOUBLE NULL DEFAULT 0,
  ATUAL DOUBLE NULL DEFAULT 0,
  IPI DOUBLE NULL,
  ICMS DOUBLE NULL,
  VENDA DOUBLE NULL DEFAULT 0,
  PS CHAR(1) NULL DEFAULT 'S',
  GRUPO INT NULL,
  DS_FABR VARCHAR(60) NULL,
  DS_LINHA VARCHAR(60) NULL,
  DS_MARCA VARCHAR(60) NULL,
  BARRAS VARCHAR(20) NULL,
  INDEX idx_produtos_descricao (DESCRICAO),
  INDEX idx_produtos_ps (PS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS knoll_servicos (
  IDSER INT NOT NULL PRIMARY KEY,
  IDCLI INT NULL,
  DT_ENTR DATETIME NULL,
  DT_SADA DATETIME NULL,
  VAL_PRO DOUBLE NULL DEFAULT 0,
  VAL_DES DOUBLE NULL DEFAULT 0,
  VAL_TOT DOUBLE NULL DEFAULT 0,
  VAL_SER DOUBLE NULL DEFAULT 0,
  IDPAG INT NULL,
  IDFUN INT NULL,
  NOME VARCHAR(80) NULL,
  IDRP INT NULL,
  USUARIO VARCHAR(40) NULL,
  EQUIPAMENTO VARCHAR(200) NULL,
  DEFEITO VARCHAR(400) NULL,
  SERVICO TEXT NULL,
  HR_ENTR CHAR(5) NULL,
  HR_SADA CHAR(5) NULL,
  HR_SERV CHAR(5) NULL,
  IN_DELT CHAR(1) NULL,
  CD_EQPM INT NULL,
  CD_AGND INT NULL,
  TIPO VARCHAR(30) NULL,
  IDPRO INT NULL,
  IN_STATUS VARCHAR(40) NULL,
  DOCUMENTO INT NULL,
  INDEX idx_servicos_cliente (IDCLI),
  INDEX idx_servicos_tecnico (IDFUN),
  INDEX idx_servicos_status (IN_STATUS),
  INDEX idx_servicos_dt_entr (DT_ENTR),
  INDEX idx_servicos_dt_sada (DT_SADA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS knoll_servicos_itens (
  IDSER INT NOT NULL,
  IDPRO INT NOT NULL,
  QTDE DOUBLE NULL DEFAULT 1,
  VAL_UNI DOUBLE NULL DEFAULT 0,
  VAL_TOT DOUBLE NULL DEFAULT 0,
  DESCRICAO VARCHAR(120) NULL,
  UNIDADE VARCHAR(10) NULL,
  DATA TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  SAIDAS DOUBLE NULL,
  PS CHAR(1) NULL DEFAULT 'P',
  IDCLI INT NULL,
  PRIMARY KEY (IDSER, IDPRO),
  INDEX idx_itens_idpro (IDPRO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS knoll_clientes_produtos (
  CD_EQPM INT NOT NULL PRIMARY KEY,
  IDGRU INT NULL,
  IDCLI INT NULL,
  DS_EQPM VARCHAR(80) NULL,
  NM_MARC VARCHAR(60) NULL,
  DS_MODL VARCHAR(60) NULL,
  DS_SERI VARCHAR(60) NULL,
  DS_OBSR VARCHAR(150) NULL,
  NU_NOTA VARCHAR(20) NULL,
  NM_SERIE VARCHAR(30) NULL,
  DT_EMSS DATETIME NULL,
  NM_REVN VARCHAR(100) NULL,
  IDSER INT NULL,
  DEFEITO VARCHAR(400) NULL,
  INDEX idx_eqpm_cliente (IDCLI),
  INDEX idx_eqpm_os (IDSER),
  INDEX idx_eqpm_desc (DS_EQPM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Usuário admin inicial (senha plaintext; login faz upgrade para bcrypt)
INSERT INTO knoll_usuarios (cd_usrs, nm_logn, cd_pass, nm_usrs, ds_email, nivel, in_tipo)
SELECT 1, 'admin', 'admin123', 'Administrador', 'admin@localhost', 1, 'A'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM knoll_usuarios WHERE cd_usrs = 1 OR nm_logn = 'admin');

INSERT INTO knoll_configuracao (nm_empr, ds_razao, sg_estd, ultimo_servico)
SELECT 'Sistema Knoll', 'Assistência Técnica', 'SC', 0
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM knoll_configuracao LIMIT 1);

INSERT INTO knoll_funcionario (IDFUN, NOME, MUNICIPIO, TIPO)
SELECT 1, 'Técnico Padrão', '', 'Tecnico'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM knoll_funcionario WHERE IDFUN = 1);
